#!/bin/bash
# Switch the active vLLM model by updating current.env and restarting the service
#
# Usage: ./switch_model.sh <model_name>
# Example: ./switch_model.sh eurollm
#
# Available models: qwen3, eurollm, mistral-small, mixtral, deepseek

set -e

MODEL=${1:-}
ENV_FILE="/workspace/vllm/current.env"
CONFIG="/workspace/ops/supervisord.conf"

if [[ -z "$MODEL" ]]; then
  echo "Usage: $0 <model_name>"
  echo ""
  echo "Available models:"
  echo "  qwen3         - Qwen3-30B-A3B-AWQ (~16-18GB, comfortable on A40)"
  echo "  eurollm       - EuroLLM-9B-Instruct (~18GB, comfortable on A40)"
  echo "  deepseek      - DeepSeek-R1-Distill-Qwen-14B (~28GB, comfortable on A40)"
  echo "  mixtral       - Mixtral-8x7B-Instruct-v0.1 (~45-50GB, MoE, tight)"
  echo "  mistral-small - Mistral-Small-3.2-24B (~48GB, VERY TIGHT, may OOM)"
  echo ""
  echo "⚠️  WARNING: mistral-small is native FP16 and may OOM on 48GB A40."
  echo "   Consider using a quantized variant or reducing max_model_len."
  exit 1
fi

# Model configurations
declare -A PATHS=(
  ["qwen3"]="/workspace/models/qwen3_30b_a3b_awq"
  ["eurollm"]="/workspace/models/eurollm_9b"
  ["mistral-small"]="/workspace/models/mistral_small_24b"
  ["mixtral"]="/workspace/models/mixtral_8x7b"
  ["deepseek"]="/workspace/models/deepseek_14b"
)

declare -A QUANT_KINDS=(
  ["qwen3"]="awq"
  ["eurollm"]=""
  ["mistral-small"]=""
  ["mixtral"]=""
  ["deepseek"]=""
)

declare -A MAX_LENS=(
  ["qwen3"]="32768"
  ["eurollm"]="8192"
  ["mistral-small"]="4096"    # Reduced for 48GB safety
  ["mixtral"]="16384"         # MoE - partial expert loading
  ["deepseek"]="16384"
)

declare -A GPU_UTILS=(
  ["qwen3"]="0.65"        # AWQ is efficient
  ["eurollm"]="0.75"
  ["mistral-small"]="0.92"  # Aggressive - may need adjustment
  ["mixtral"]="0.90"        # MoE loads partial experts
  ["deepseek"]="0.75"
)

# Validate model name
if [[ -z "${PATHS[$MODEL]:-}" ]]; then
  echo "ERROR: Unknown model '${MODEL}'"
  echo "Available: ${!PATHS[*]}"
  exit 1
fi

# Check if model directory exists
if [[ ! -d "${PATHS[$MODEL]}" ]]; then
  echo "ERROR: Model directory not found: ${PATHS[$MODEL]}"
  echo "Run download_models.sh first to download the models."
  exit 1
fi

echo "🔄 Stopping current vLLM instance..."
supervisorctl -c "$CONFIG" stop vllm 2>/dev/null || true

# Kill any lingering vLLM processes (this actually frees VRAM)
pkill -f "vllm serve" 2>/dev/null || true
sleep 3

# Write env file (clean, no regex shenanigans)
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" << EOF
# Auto-generated by switch_model.sh
# Do not edit manually - use switch_model.sh instead
MODEL_NAME=${MODEL}
MODEL_PATH=${PATHS[$MODEL]}
QUANT_KIND=${QUANT_KINDS[$MODEL]}
MAX_MODEL_LEN=${MAX_LENS[$MODEL]}
GPU_MEM_UTIL=${GPU_UTILS[$MODEL]}
API_KEY=${VLLM_API_KEY:-change-me-to-secure-key}
EOF

echo "🚀 Starting ${MODEL}..."
supervisorctl -c "$CONFIG" start vllm

echo ""
echo "✅ Switch initiated. Monitor logs with:"
echo "   supervisorctl -c ${CONFIG} tail -f vllm"
